name: MGGungame
main: com.comze_instancelabs.gungame.Main
version: 1.6.6
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   gg:
      description: Main command
      usage: /gg [action]
      aliases: [gungame, mggungame]
   gp:
      description: GP command
      usage: /gp
